/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.User;

/**
 *
 * @author ridhogymnastiar
 */
public class LoginRegister extends javax.swing.JFrame {

    /**
     * Creates new form LoginRegister
     */
    private final factory.UserFactory uf;

    public LoginRegister(factory.UserFactory uf) {
        this.uf = uf;
        initComponents();
        panelLogin.setVisible(true);
        panelRegister.setVisible(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnChooseRegister = new javax.swing.JButton();
        btnChooseLogin = new javax.swing.JButton();
        panelLogin = new javax.swing.JPanel();
        tfLoginEmail = new javax.swing.JTextField();
        tfLoginPassword = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        panelRegister = new javax.swing.JPanel();
        tfRegisterEmail = new javax.swing.JTextField();
        tfRegisterUsername = new javax.swing.JTextField();
        tfRegisterPassword = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnChooseRegister.setText("Register");
        btnChooseRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(btnChooseRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 230, 50));

        btnChooseLogin.setText("Login");
        btnChooseLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnChooseLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 230, 50));

        panelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfLoginEmail.setText("email");
        panelLogin.add(tfLoginEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 300, 50));

        tfLoginPassword.setText("password");
        panelLogin.add(tfLoginPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 300, 50));

        btnLogin.setForeground(new java.awt.Color(242, 242, 242));
        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Group 2 (2).png"))); // NOI18N
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        panelLogin.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 230, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/1655347575-rute-transjakarta.jpg"))); // NOI18N
        panelLogin.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel1.add(panelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 630, 370));

        panelRegister.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfRegisterEmail.setText("email");
        panelRegister.add(tfRegisterEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 300, 50));

        tfRegisterUsername.setText("username");
        panelRegister.add(tfRegisterUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 300, 50));

        tfRegisterPassword.setText("password");
        panelRegister.add(tfRegisterPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 300, 50));

        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        panelRegister.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 230, 50));

        jPanel1.add(panelRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 630, 370));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnChooseLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseLoginActionPerformed
        // TODO add your handling code here:
        panelLogin.setVisible(true);
        panelRegister.setVisible(false);
    }//GEN-LAST:event_btnChooseLoginActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        var email = tfRegisterEmail.getText();
        var username = tfRegisterUsername.getText();
        var password = tfRegisterPassword.getText();
        uf.insert(new User(email, username, password));
        JOptionPane.showMessageDialog(null, "Register Berhasil!");
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnChooseRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseRegisterActionPerformed
        // TODO add your handling code here:
        panelLogin.setVisible(false);
        panelRegister.setVisible(true);
    }//GEN-LAST:event_btnChooseRegisterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChooseLogin;
    private javax.swing.JButton btnChooseRegister;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPanel panelRegister;
    private javax.swing.JTextField tfLoginEmail;
    private javax.swing.JTextField tfLoginPassword;
    private javax.swing.JTextField tfRegisterEmail;
    private javax.swing.JTextField tfRegisterPassword;
    private javax.swing.JTextField tfRegisterUsername;
    // End of variables declaration//GEN-END:variables
}
